#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : cantata
Version  : 2.4.1
Release  : 10
URL      : https://github.com/CDrummond/cantata/releases/download/v2.4.1/cantata-2.4.1.tar.bz2
Source0  : https://github.com/CDrummond/cantata/releases/download/v2.4.1/cantata-2.4.1.tar.bz2
Summary  : Qt5 client for the music player daemon (MPD)
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 GPL-3.0 LGPL-2.1 MIT
Requires: cantata-bin = %{version}-%{release}
Requires: cantata-data = %{version}-%{release}
Requires: cantata-license = %{version}-%{release}
Requires: media-player-info
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : media-player-info
BuildRequires : pkg-config
BuildRequires : pkgconfig(libmpg123)
BuildRequires : pkgconfig(libmtp)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : systemd-dev
BuildRequires : taglib-dev
BuildRequires : zlib-dev

%description
Table of Contents
=================
1. Introduction
2. Dependencies
3. Building
4. Bugs
5. Translations
6. Covers
7. CUE Files
8. Streams
9. MultiMedia Keys
10. DBUS Actions
11. Dynamic Helper Script - Local Mode
12. Dynamic Helper Script - Server Mode
13. Source Code
14. Debug Logging
15. Credits
16. Windows
17. Mac OSX

%package bin
Summary: bin components for the cantata package.
Group: Binaries
Requires: cantata-data = %{version}-%{release}
Requires: cantata-license = %{version}-%{release}

%description bin
bin components for the cantata package.


%package data
Summary: data components for the cantata package.
Group: Data

%description data
data components for the cantata package.


%package license
Summary: license components for the cantata package.
Group: Default

%description license
license components for the cantata package.


%prep
%setup -q -n cantata-2.4.1
cd %{_builddir}/cantata-2.4.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583778969
mkdir -p clr-build
pushd clr-build
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1583778969
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cantata
cp %{_builddir}/cantata-2.4.1/3rdparty/ebur128/COPYING %{buildroot}/usr/share/package-licenses/cantata/2627ff03833f74ed51a7f43c55d30b249b6a0707
cp %{_builddir}/cantata-2.4.1/3rdparty/kcategorizedview/COPYING %{buildroot}/usr/share/package-licenses/cantata/7c203dee3a03037da436df03c4b25b659c073976
cp %{_builddir}/cantata-2.4.1/3rdparty/kcategorizedview/COPYING.LIB %{buildroot}/usr/share/package-licenses/cantata/9a1929f4700d2407c70b507b3b2aaf6226a9543c
cp %{_builddir}/cantata-2.4.1/3rdparty/qtiocompressor/LICENSE.GPL3 %{buildroot}/usr/share/package-licenses/cantata/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/cantata-2.4.1/3rdparty/qtsingleapplication/LICENSE.LGPL %{buildroot}/usr/share/package-licenses/cantata/caeb68c46fa36651acf592771d09de7937926bb3
cp %{_builddir}/cantata-2.4.1/3rdparty/qxt/LICENSE %{buildroot}/usr/share/package-licenses/cantata/3f3ade74b4071609a90853616f8db5f76a3db568
cp %{_builddir}/cantata-2.4.1/LICENSE %{buildroot}/usr/share/package-licenses/cantata/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/cantata-2.4.1/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/cantata/57c3cb6b9aee09ae2af06b0c517e2969d2f33d47
cp %{_builddir}/cantata-2.4.1/windows/LICENSE.txt %{buildroot}/usr/share/package-licenses/cantata/7713a1753ce88f2c7e6b054ecc8e4c786df76300
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib/cantata/cantata-replaygain
/usr/lib/cantata/cantata-tags

%files bin
%defattr(-,root,root,-)
/usr/bin/cantata

%files data
%defattr(-,root,root,-)
/usr/share/applications/cantata.desktop
/usr/share/cantata/icons/podcasts.png
/usr/share/cantata/icons/soundcloud.png
/usr/share/cantata/icons/stream.png
/usr/share/cantata/scripts/cantata-dynamic
/usr/share/cantata/scripts/cantata-remote
/usr/share/cantata/translations/cantata_cs.qm
/usr/share/cantata/translations/cantata_da.qm
/usr/share/cantata/translations/cantata_de.qm
/usr/share/cantata/translations/cantata_en_GB.qm
/usr/share/cantata/translations/cantata_es.qm
/usr/share/cantata/translations/cantata_fi.qm
/usr/share/cantata/translations/cantata_fr.qm
/usr/share/cantata/translations/cantata_hu.qm
/usr/share/cantata/translations/cantata_it.qm
/usr/share/cantata/translations/cantata_ja.qm
/usr/share/cantata/translations/cantata_ko.qm
/usr/share/cantata/translations/cantata_nl.qm
/usr/share/cantata/translations/cantata_pl.qm
/usr/share/cantata/translations/cantata_pt_BR.qm
/usr/share/cantata/translations/cantata_ru.qm
/usr/share/cantata/translations/cantata_zh_CN.qm
/usr/share/icons/hicolor/128x128/apps/cantata.png
/usr/share/icons/hicolor/16x16/apps/cantata.png
/usr/share/icons/hicolor/22x22/apps/cantata.png
/usr/share/icons/hicolor/24x24/apps/cantata.png
/usr/share/icons/hicolor/256x256/apps/cantata.png
/usr/share/icons/hicolor/32x32/apps/cantata.png
/usr/share/icons/hicolor/48x48/apps/cantata.png
/usr/share/icons/hicolor/512x512/apps/cantata.png
/usr/share/icons/hicolor/64x64/apps/cantata.png
/usr/share/icons/hicolor/scalable/apps/cantata.svg
/usr/share/icons/hicolor/symbolic/apps/cantata-symbolic.svg

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cantata/2627ff03833f74ed51a7f43c55d30b249b6a0707
/usr/share/package-licenses/cantata/3f3ade74b4071609a90853616f8db5f76a3db568
/usr/share/package-licenses/cantata/57c3cb6b9aee09ae2af06b0c517e2969d2f33d47
/usr/share/package-licenses/cantata/7713a1753ce88f2c7e6b054ecc8e4c786df76300
/usr/share/package-licenses/cantata/7c203dee3a03037da436df03c4b25b659c073976
/usr/share/package-licenses/cantata/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/cantata/9a1929f4700d2407c70b507b3b2aaf6226a9543c
/usr/share/package-licenses/cantata/caeb68c46fa36651acf592771d09de7937926bb3
